---
- name: Destroy
  hosts: all
  connection: local
  gather_facts: false
  roles:
    - erjac77.f5

  tasks:
    - name: Delete LTM Pools
      f5bigip_ltm_pool:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        partition: "{{ partition.name }}"
        state: absent
      delegate_to: localhost
      loop: "{{ pools }}"

    - name: Delete LTM Nodes
      f5bigip_ltm_node:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        partition: "{{ partition.name }}"
        state: absent
      delegate_to: localhost
      loop: "{{ nodes }}"

    - name: Delete Auth Partition
      f5bigip_auth_partition:
        provider: "{{ provider }}"
        name: "{{ partition.name }}"
        state: absent
      delegate_to: localhost
