---
- name: Converge
  hosts: all
  connection: local
  gather_facts: false
  roles:
    - erjac77.f5

  tasks:
    - name: Create GTM FTP Monitor
      f5bigip_gtm_monitor_ftp:
        provider: "{{ provider }}"
        name: "{{ monitor.name }}"
        partition: "{{ monitor.partition | default(omit) }}"
        description: "{{ monitor.description | default(omit) }}"
        state: present
      delegate_to: localhost
