---
- name: Cleanup
  hosts: all
  connection: local
  gather_facts: false
  roles:
    - erjac77.f5

  tasks:
    - name: Delete GTM HTTPS Monitor
      f5bigip_gtm_monitor_https:
        provider: "{{ provider }}"
        name: "{{ monitor.name }}"
        partition: "{{ monitor.partition | default(omit) }}"
        state: absent
      delegate_to: localhost
