---
- name: Cleanup
  hosts: all
  connection: local
  gather_facts: false
  roles:
    - erjac77.f5

  tasks:
    - name: Delete GTM Listener
      f5bigip_gtm_listener:
        provider: "{{ provider }}"
        name: "{{ listener.name }}"
        partition: "{{ listener.partition | default('Common') }}"
        state: absent
      delegate_to: localhost
