---
- name: Cleanup
  hosts: all
  connection: local
  gather_facts: false
  roles:
    - erjac77.f5

  tasks:
    - name: Delete GTM Datacenter
      f5bigip_gtm_datacenter:
        provider: "{{ provider }}"
        name: "{{ datacenter.name }}"
        state: absent
      delegate_to: localhost
