---
- name: Cleanup
  hosts: all
  connection: local
  gather_facts: false
  roles:
    - erjac77.f5

  tasks:
    - name: Delete CM Traffic Group
      f5bigip_cm_traffic_group:
        provider: "{{ provider }}"
        name: "{{ traffic_group.name }}"
        state: absent
      delegate_to: localhost
