---
- name: Converge
  hosts: all
  connection: local
  gather_facts: false
  roles:
    - erjac77.f5

  tasks:
    - name: Get CM failover status of the device
      f5bigip_cm_failover_status:
        provider: "{{ provider }}"
      register: result
      delegate_to: localhost

    - name: Display the failover status of the device
      debug:
        msg: "Failover Status: {{ result.status }}"
      when: result.status is defined

    - name: Assert Get CM failover status of the device
      assert:
        that:
          - result.status == 'ACTIVE'
      when: result.status is defined
