---
- name: Converge
  hosts: all
  connection: local
  gather_facts: false
  roles:
    - erjac77.f5

  tasks:
    - name: Create Auth Partition
      f5bigip_auth_partition:
        provider: "{{ provider }}"
        name: "{{ partition.name }}"
        description: "{{ partition.description | default(omit) }}"
        state: present
      delegate_to: localhost
