---
- name: Cleanup
  hosts: all
  connection: local
  gather_facts: false
  roles:
    - erjac77.f5

  tasks:
    - name: Add self device to CM Trust Domain
      f5bigip_cm_trust_domain:
        provider: "{{ provider }}"
        name: "{{ trust_domain.name }}"
        ca_devices: "{{ trust_domain.ca_devices | default(omit) }}"
        state: present
      delegate_to: localhost
